### ISSUE TITLE
0.29 update documentation about OPT_UNSAFE

### ISSUE THREAD

**Issue by bes-internal** [nwellnhof/perl-commonmark#10]
please update the documentation in pod:
- parse option
- Parser options section
- if possible, detail with examples show how to work with "$ options is a bit field containing the parser options"
- is what really OPT_DEFAULT?

**Comment by nwellnhof** [comment]
The documentation of OPT_UNSAFE was updated with the commit introducing it: https://github.com/nwellnhof/perl-commonmark/commit/a6e4053e671370c6bdcac40fdf267bd69f2dea1f

Using a bit field for options (which are typically combined with binary OR) is a widely-used concept. OPT_DEFAULT equals 0, so it doesn't set any options.
