### ISSUE TITLE
Parse Does not Preserve Formatting Options

### ISSUE THREAD

**Issue by theory** [nwellnhof/perl-commonmark#13]
The docs say about the `parse` method:

``` pod
Convenience function to parse documents. Exactly one of the C<string> or
C<file> options must be provided. When given a string, calls
L</parse_document>. When given a file, calls L</parse_file>. C<normalize>,
C<smart>, and C<validate_utf8> enable the respective
L<parser options|/"Parser options">.
```

This may be true for parsing options but not for formatting options. In other words, this code:

``` perl
CommonMark->parse(string => 'foo --- bar', smart => 1)->render_html;
```

Correctly returns:

``` html
<p>foo — bar</p>
```

However, this code:

``` perl
CommonMark->parse(string => 'foo --- bar', sourcepos => 1)->render_html;
```

Does not. It returns:

``` html
<p>foo --- bar</p>
```

What I expected was:

``` html
<p data-sourcepos="1:1-1:11">foo --- bar</p>
```

The reason it does not work is that the parser ignores format options, and they are not retained in the document to be handed off to `render_html` When it's called. The fix would be to retain the options bit field in the document and pass it to `render_html`.

I see that the integral options can be passed to `render_html`, so this code:

``` perl
CommonMark->parse(string => 'foo --- bar')->render_html(OPT_SOURCEPOS);
```

Does render correctly. I take from this it's best to use the C-based functions and not the string parameters, but for usability sake it'd be nice to support string parameters more consistently.

**Comment by theory** [comment]
My workaround, BTW, is:

``` perl
sub parse {
    my $str = shift;
    my $opts = CommonMark::_extract_opts({@_});
    return CommonMark->parse_document($str, $opts)->render_html($opts);
}
```

Ugly to use a private function, of course.

**Comment by nwellnhof** [comment]
This is all by design. Parser and render options should be separated. It doesn't make sense to associate a fixed set of render options with a document.
