### ISSUE TITLE
Tests Crash on Windows

### ISSUE THREAD

**Issue by theory** [nwellnhof/perl-commonmark#15]
Discovered as part of #12, and demonstrated in [this 5.32 build on Windows](https://github.com/theory/perl-commonmark/actions/runs/6148615381/job/16682691309), tests `t/02_accessors.t` and `t/10_wrappers.t` appear to crash after running a single test. I did a little debugging [in this build](https://github.com/theory/perl-commonmark/actions/runs/6148615381/job/16682691309), and it looks like both crash on the call to `CommonMark->parse_file`, which is defined in [this XS code](/nwellnhof/perl-commonmark/blob/4e0aa28/CommonMark.xs#L316-L338). Perhaps there's something there or in the cmark library's `cmark_parse_file` that isn't compatible with Windows?

**Comment by nwellnhof** [comment]
I don't have time to debug issues on Windows right now. Might be related to PerlIO.

**Comment by theory** [comment]
Yeah, I asked on Mastodon for thoughts, no takers. I'm sure someone who knows XS and Windows stuff can figure it out quickly. Alas, I know little about either myself. :-(

**Comment by nwellnhof** [comment]
FWIW, the Appveyor tests on Windows passed with 0.290000: https://ci.appveyor.com/project/nwellnhof/perl-commonmark. But for some reason, the new commits didn't trigger a test run.

**Comment by theory** [comment]
Huh, odd. I wonder if there's some difference in compiler toolchains at work here…

**Comment by nwellnhof** [comment]
The main difference is that the Appveyor tests are run under ActivePerl.

**Comment by theory** [comment]
Oh, interesting. The [perl setup action](/shogo82148/actions-setup-perl) uses plain old Perl, though there is an option to use [Strawberry Perl](https://strawberryperl.com). I wonder if it'd work there.

**Comment by nwellnhof** [comment]
Fixed with bf07b5e and b5369d9.
