### ISSUE TITLE
Install error; missing dependency?

### ISSUE THREAD

**Issue by shawnhcorey** [nwellnhof/perl-commonmark#5]
When I try to install CommonMark, I get the following error. Is there a dependency I'm missing?

```
$ cpanm Commonmark
! Configure failed for CommonMark-0.240100. See /home/shawn/.cpanm/work/1507812474.7313/build.log for details.
```
And the log file does not exist.

**Comment by shawnhcorey** [comment]
There is a hidden dependency:
```
--> Working on CommonMark
Fetching http://www.cpan.org/authors/id/N/NW/NWELLNHOF/CommonMark-0.240100.tar.gz
-> OK
Unpacking CommonMark-0.240100.tar.gz
Entering CommonMark-0.240100
Checking configure dependencies from META.yml
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.10_02)
Checking if you have Devel::CheckLib 0 ... Yes (1.11)
Configuring CommonMark-0.240100
Running Makefile.PL
libcmark 0.21.0 or higher not found at Makefile.PL line 16.
```

A version of `cmark` needs be present. You should add this to the documentation.

**Comment by nwellnhof** [comment]
It's explained in the [README](https://github.com/nwellnhof/perl-commonmark). Where else did you expect this to be documented?

**Comment by shawnhcorey** [comment]
In https://metacpan.org/pod/distribution/CommonMark/lib/CommonMark.pod

The POD is not up to date.

**Comment by nwellnhof** [comment]
I originally  made the decision to put installation instructions into README.pod and the distro documentation in the other .pod files. CommonMark.pod is the probably the file that most users read first, so it makes sense to put some installation instructions in there, either by

1. mentioning the README file,
2. duplicating the infomation in README, or
3. moving the README contents completely.

Personally, I'd prefer (1), but MetaCPAN refuses to display the README.pod file for dubious reasons (https://github.com/metacpan/metacpan-web/issues/1482). (2) complicates maintenance, so (3) seems like the best option to me. What do you think?

**Comment by shawnhcorey** [comment]
Personally, I would make the effort to merge them. I think Github can read a symbolic-linked README file, so this should work:
```bash
ln -s CommonMark.pod README.pod
```
